server:
  port: 8090

springdoc:
  api-docs:
    enabled: true
    path: /api-doc
  swagger-ui:
    path: /swagger-ui.html

spring:
  jackson:
    serialization:
      write-dates-as-timestamps: false
  security:
    user:
      name: test1
      password: test2
  datasource:
    url: jdbc:h2:mem:testdb
  h2:
    console:
      enabled: true
  jpa:
    defer-datasource-initialization: true
    show-sql: true
  data:
    jpa:
      repositories:
        bootstrap-mode: default



management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: "*"